ecommerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('main_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_app/urls.py
from django.urls import include, path
from .views import CartSummaryView, HomeView, ItemDetailView, CheckoutView, ProfileView, AddressView, OrderView, \
                AddCouponView, RemoveCouponView, RefundView, \
                add_item_to_cart, remove_item_from_cart, delete_item_from_cart

urlpatterns = [
    # Home page
    path('', HomeView.as_view(), name='home-page'),
    path('category/<slug>/', HomeView.as_view(), name='home-page'),
    path('search/', HomeView.as_view(), name='search-query'),

    # Profile
    path('profile/address/<crud>/<dest>/', AddressView.as_view(), name='profile-user-address'),
    path('profile/address/<crud>/<address>/<number>/<zipcode>/<dest>/', AddressView.as_view(), name='profile-user-address'),
    path('profile/user-data/', ProfileView.as_view(), name='profile-user-data'),
    path('profile/user-orders/', OrderView.as_view(), name='profile-user-orders'),

    # Product
    path('product/<slug>/<pk>/', ItemDetailView.as_view(), name='product'),

    # Cart
    path('mycart/', CartSummaryView.as_view(), name='mycart'),
    path('cart-item/add/<slug>/<pk>/<dest>/', add_item_to_cart, name='add-item-to-cart'),
    path('cart-item/remove/<slug>/<pk>/<dest>/', remove_item_from_cart, name='remove-item-from-cart'),
    path('cart-item/delete/<slug>/<pk>/<dest>/', delete_item_from_cart, name='delete-item-from-cart'),

    # Coupon
    path('coupon/add/', AddCouponView.as_view(), name='add-coupon'),
    path('coupon/remove/<dest>/', RemoveCouponView.as_view(), name='remove-coupon'),

    # Order summary
    path('checkout/', CheckoutView.as_view(), name='checkout'),

    # Payment
    path('payments/', include('mercadopago_payment.urls', namespace='payments')),

    # Refund
    path('refund-request/', RefundView.as_view(), name='refund-request'),
    path('refund-request/<cod>/', RefundView.as_view(), name='refund-request'),    
]

main_app/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django.db.models.signals import post_save
from localflavor.br.models import BRCPFField, BRPostalCodeField, BRStateField
from django.dispatch import receiver
from allauth.account.models import EmailAddress
from allauth.account.signals import email_confirmed
from django.utils.text import slugify

LABEL_OPTIONS = (
    ('N', 'Novo'),
    ('D', 'Em Destaque'),
    ('P', 'Promoção'),
)

class UserProfile(models.Model):
    class Meta:
        verbose_name="Perfi"
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    cpf = BRCPFField("CPF")
    full_name = models.CharField("Nome Completo", max_length=200)
    cell_number = models.CharField("Celular", max_length=15, blank=True, null=True)

    def __str__(self):
        return self.user.username
    def add_email_address(self, request, new_email):
        # Add a new email address for the user, and send email confirmation.
        # Old email will remain the primary until the new one is confirmed.
        return EmailAddress.objects.add_email(request, self.user, new_email, confirm=True)

@receiver(email_confirmed)
def update_user_email(sender, request, email_address, **kwargs):
    # Get rid of old email addresses
    # email_address is an instance of allauth.account.models.EmailAddress
    EmailAddress.objects.filter(user=email_address.user).exclude(primary=True).delete()
    # Once the email address is confirmed, make new email_address primary.
    # This also sets user.email to the new email address.
    email_address.set_as_primary()


class Category(models.Model):
    class Meta:
        verbose_name="Categoria"
    title = models.CharField(max_length=200)
    description = models.TextField()
    slug = models.SlugField(unique=True, max_length=255)
    # slug = models.SlugField()

    def save(self, *args, **kwargs):
        super(Category, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.title) + "-" + str(self.id)
            self.save()
    def __str__(self):
        return self.title


class Item(models.Model):
    class Meta:
        verbose_name="Produto"
        ordering = ['id']
    title = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    discount_price = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True) # discount is not mandatory
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, blank=True, null=True)
    label = models.CharField(choices=LABEL_OPTIONS, max_length=1, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    slug = models.SlugField(unique=True, max_length=255)
    image = models.ImageField()

    def __str__(self):
        return self.title
    def get_url(self):
        return reverse("product", kwargs={'slug': self.slug, 'pk': self.id})
    def get_add_item_to_cart_url(self):
        return reverse("add-item-to-cart", kwargs={'slug': self.slug, 'pk': self.id, 'dest': 'product'})
    def get_remove_item_from_cart_url(self):
        return reverse("remove-item-from-cart", kwargs={'slug': self.slug, 'pk': self.id, 'dest': 'product'})
    def get_delete_item_from_cart_url(self):
        return reverse("delete-item-from-cart", kwargs={'slug': self.slug, 'pk': self.id, 'dest': 'product'})

class OrderItem(models.Model):
    class Meta:
        verbose_name="ItemsCarrinho"
    user_order = models.ForeignKey('Order', on_delete=models.CASCADE, blank=True, null=True)
    item = models.ForeignKey('Item', on_delete=models.CASCADE) # if the item was deleted, the orderitem will be removed also.
    quantity = models.IntegerField(default=1)
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, # user currently logged in django
    #                          on_delete=models.CASCADE)
    finished = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} de {self.item.title}"
    def get_total_price(self):
        return self.quantity * self.item.price
    def get_total_discount_price(self):
        return self.quantity * self.item.discount_price
    def get_discount_amount(self):
        return self.get_total_price() - self.get_total_discount_price()

class Order(models.Model):
    class Meta:
        verbose_name="Pedido"
    user = models.ForeignKey(settings.AUTH_USER_MODEL, # user currently logged in django
                             on_delete=models.CASCADE,
                             verbose_name="Cliente")
    start_date = models.DateTimeField("Iniciado em:", auto_now_add=True)
    finished = models.BooleanField("Finalizado", default=False) # this field can be replaced, if date is not set it means the it is not finished
    finished_date = models.DateTimeField("Finalizado em:", blank=True, null=True)
    items = models.ManyToManyField('OrderItem')
    billing_address = models.ForeignKey('BillingAddress', verbose_name="Endereço",
                                        on_delete=models.CASCADE,
                                        blank=True, null=True)
    paid = models.BooleanField("Pago", default=False)
    payment = models.ForeignKey('mercadopago_payment.Payment', verbose_name="Pagamento", related_name="mercadopago",
                                on_delete=models.CASCADE,
                                blank=True, null=True)
    coupon = models.ForeignKey('Coupon', verbose_name="Cupom",
                                on_delete=models.CASCADE,
                                blank=True, null=True)
    on_the_road = models.BooleanField("Na estrada", default=False)
    delivered = models.BooleanField("Entregue", default=False)
    refund_requested = models.BooleanField("Desistencia Solicitada", default=False)
    refund_accepted = models.BooleanField("Desistencia Aceita", default=False)
    # ref_code = models.CharField(max_length=32, blank=True, null=True)
    ref_code = models.UUIDField(blank=True, null=True)

    def __str__(self):
        return self.user.username
    def get_total_price(self):
        result = 0
        for order_item in self.items.all():
            if order_item.item.discount_price:
                result += order_item.get_total_discount_price()
            else:
                result += order_item.get_total_price()
        return result
    def get_total(self):
        result = self.get_total_price()
        if self.coupon:
            result -= self.coupon.amount
        return result
    def get_total_items(self):
        result = 0
        for order_item in self.items.all():
            result += order_item.quantity
        return result
    def get_description(self):
        return ", ".join(
            [f"{order_item.quantity} x {order_item.item.title}" for order_item in self.items.all()]
        )

class BillingAddress(models.Model):
    class Meta:
        verbose_name="Endereço"
    user = models.ForeignKey(settings.AUTH_USER_MODEL, # user currently logged in django
                             on_delete=models.CASCADE)
    address = models.CharField(max_length=250)
    number = models.IntegerField()
    city = models.CharField(max_length=250)
    state = models.CharField(max_length=250)
    district = models.CharField(max_length=250)
    # state = BRStateField()
    zipcode = BRPostalCodeField()
    complement = models.CharField(max_length=250, blank=True)
    is_active = models.BooleanField(default=True)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address}, {self.number} - {self.city}, {self.state}"


class Coupon(models.Model):
    class Meta:
        verbose_name="Cupom"
    code = models.CharField(max_length=15)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

class Refund(models.Model):
    class Meta:
        verbose_name="Desistência"
    user_order = models.ForeignKey('Order',
                                    on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return str(self.pk)

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        # userprofile = UserProfile.objects.create(user=instance, email=instance.email)
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>My E-commerce</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">

  {% block extra_head %}{% endblock %}
</head>


<body style="height: 100vh;">
  {% include "navbar.html" %}


  {% if messages %}
    <div>
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    </div>
  {% endif %}

  <div style="min-height: 76%;">
    {% block content %}{% endblock %}
  </div>

  {% include "footer.html" %}


  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js" integrity="sha512-n/4gHW3atM3QqRcbCn6ewmpxcLAHGaDjpEBu4xZd47N0W2oQ+6q7oc3PXstrJYXcbNU1OHdQ1T7pAP+gi5Yu8g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

  <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
  <script type="text/javascript">
    var user = '{{ request.user }}';
    function getCookie(name) {
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");

        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
            var cookiePair = cookieArr[i].split("=");

            /* Removing whitespace at the beginning of the cookie name
            and compare it with the given string */
            if(name == cookiePair[0].trim()) {
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1]);
            }
        }

        // Return null if not found
        return null;
    }
    var cart = JSON.parse(getCookie('cart'))

    if (cart == undefined){
        cart = {}
        console.log('Cart Created!', cart)
        document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/;max-age=604800" //1 week
    }
    console.log('Cart:', cart);
  </script>

  {% block extra_scripts %}{% endblock %}
</body>

</html>

templates/cart-snippet.html
{% load cart_template_tags %}

<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Carrinho</span>
    <span class="badge badge-secondary badge-pill">{{ order.get_total_items }}</span>
</h4>

<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
    {% for product in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed" style="align-items: center;">
        <span>{{ product.quantity }} x {{ product.item.title|truncatewords_html:5 }}</span>

        <div class="text-right">
            {% if product.item.discount_price %}
                {{ product.get_total_discount_price|currency_format }}
                <div>
                    <span class="badge badge-primary">Economia de ${{ product.get_discount_amount|currency_format }}</span>
                </div>
            {% else %}
                {{ product.get_total_price|currency_format }}
            {% endif %}
        </div>

    </li>
    {% endfor %}

    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light" style="align-items: center;">
        <div class="text-success">
            <h6 class="my-0">Cupom</h6>
            <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-{{ order.coupon.amount|currency_format }}</span>
        {% if add_coupon_feature %}
        <form class="" method="POST" action="{% url 'remove-coupon' 'checkout' %}">
            {% csrf_token %}
            <button class="btn btn-danger btn-sm" type="submit">X</button>
        </form>
        {% endif %}
    </li>
    {% endif %}

    <li class="list-group-item d-flex justify-content-between">
        <span>Total (BRL)</span>
        <strong id="totalAmount">{{ order.get_total|currency_format }}</strong>
    </li>
</ul>
<!-- Cart -->

<!-- Promo code -->
{% if add_coupon_feature %}
<form class="card p-2" method="POST" action="{% url 'add-coupon' %}">
    {% csrf_token %}
    <div class="input-group">
    {{ coupon_form.code }}
    
    <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Aplicar</button>
    </div>
    </div>
</form>
<!-- Promo code -->
{% endif %}

templates/footer.html
<!--Footer-->
<footer class="text-center font-small mt-auto wow fadeIn" style="background: rgba(23, 25, 26, 0.185);">

  <!--<hr class="my-4">-->

  <!-- Social icons -->
  <div class="pb-4 pt-4">
    <a href="https://www.facebook.com/mdbootstrap" target="_blank">
      <i class="fab fa-facebook-f mr-3"></i>
    </a>

    <a href="https://twitter.com/MDBootstrap" target="_blank">
      <i class="fab fa-twitter mr-3"></i>
    </a>

    <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
      <i class="fab fa-youtube mr-3"></i>
    </a>

    <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
      <i class="fab fa-google-plus-g mr-3"></i>
    </a>

    <a href="https://dribbble.com/mdbootstrap" target="_blank">
      <i class="fab fa-dribbble mr-3"></i>
    </a>

    <a href="https://pinterest.com/mdbootstrap" target="_blank">
      <i class="fab fa-pinterest mr-3"></i>
    </a>

    <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
      <i class="fab fa-github mr-3"></i>
    </a>

    <a href="http://codepen.io/mdbootstrap/" target="_blank">
      <i class="fab fa-codepen mr-3"></i>
    </a>
  </div>
  <!-- Social icons -->

  <!--Copyright-->
  <div class="footer-copyright py-3">
    © 2019 Copyright:
    <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
  </div>
  <!--/.Copyright-->

</footer>
<!--/.Footer-->

templates/home-page.html
{% extends "base.html" %}
{% load cart_template_tags %}
{% load static %}

{% block extra_head %}
<style>
  /* used to show unavailable over the product */
  .text-block {
    background-color: black;
    color: white;
    position: absolute;
    text-align: center;
    width: 100%;
  }
</style>
{% endblock %}

{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-light mt-5 mb-5" style="background: rgba(23, 25, 26, 0.185);">

        <!-- Navbar brand -->
        <span class="navbar-brand text-primary">Categorias:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Tudo
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for category in category_list %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home-page' category.slug %}">{{ category.title }}</a>
              </li>
            {% endfor %}

          </ul>
          <!-- Links -->

        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for product in object_list %}
          
          <div class="col-lg-3 col-md-4 mb-4" style="max-width: none;">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <a href="{{ product.get_url }}">
                {% if product.quantity > 0 %}
                  <img src="{{ product.image.url }}" height="250px">
                {% else %}
                  <img src="{{ product.image.url }}" height="250px" style="filter: grayscale(1);">
                  <div class="text-block">
                    <h4>Indisponível</h4>
                  </div>
                {% endif %}
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center" style="min-height: 250px;">
                <a href="{{ product.get_url }}" class="dark-grey-text">
                  <h5>
                    <strong>{{ product.title|truncatewords_html:7 }}</strong>
                    <br>
                    {% if product.get_label_display %}

                      {% if product.label == 'N' %}
                      <div class="badge badge-primary">{{ product.get_label_display }}</div>
                      {% elif product.label == 'D' %}
                      <div class="badge badge-danger">{{ product.get_label_display }}</div>
                      {% elif product.label == 'P' %}
                      <div class="badge badge-warning">{{ product.get_label_display }}</div>
                      {% endif %}
                    {% else %}
                      <div class="badge badge-primary" style="visibility: hidden;">Normal</div>
                    {% endif %}
                  </h5>
                </a>


                <!--Category & Title-->
                <div style="font-size: 12px;">
                  {% if product.category %}
                    Categoria: <a href="{% url 'home-page' product.category.slug %}">{{ product.category }}</a>
                  {% else %}
                    Categoria: Outros
                  {% endif %}
                </div>


                {% if product.discount_price %}
                  <del style="font-size: 12px;">{{ product.price|currency_format }}</del>
                  <h4 class="font-weight-bold">
                    <strong>{{ product.discount_price|currency_format }}</strong>
                  </h4>
                {% else %}
                  <del style="visibility: hidden;">{{ product.price|currency_format }}</del>
                  <h4 class="font-weight-bold">
                    <strong>{{ product.price|currency_format }}</strong>
                  </h4>
                {% endif %}


                <a href="{% url 'add-item-to-cart' product.slug product.pk 'cart' %}" class="update-cart btn btn-primary btn-block" data-action="add" data-slug="{{ product.slug }}" data-pk="{{ product.pk }}">
                  Comprar
                  <i class="fas fa-shopping-cart ml-1"></i>
                </a>


              </div>
              <!--Card content-->

            </div>
            <!--Card-->
          </div>

          {% empty %}
          <div class="col-lg-12 mb-4">
            <strong class='text-center'>Nenhum produto encontrado!</strong>
          </div>
          {% endfor %}

        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <!--Arrow left-->
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
  {% endblock %}

templates/product.html
{% extends "base.html" %}
{% load cart_template_tags %}

{% block content %}
<!--Main layout-->
<main>
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4 text-center">

        <img src="{{ product.image.url }}" width="250px" height="150px" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{ product.category.title }}</span>
            </a>
          </div>

          <p class="lead font-weight-bold">
            {{ product.title }}
            {% if product.get_label_display %}
              {% if product.label == 'N' %}
              <span class="badge badge-pill badge-primary">{{ product.get_label_display }}</span>
              {% elif product.label == 'D' %}
              <span class="badge badge-pill badge-danger">{{ product.get_label_display }}</span>
              {% elif product.label == 'P' %}
              <span class="badge badge-pill badge-warning">{{ product.get_label_display }}</span>
              {% endif %}
            {% endif %}
          </p>


          <p class="lead">
            {% if product.discount_price %}
              <span class="mr-1">
                <del>{{ product.price|currency_format }}</del>
              </span>
              <span>{{ product.discount_price|currency_format }}</span>
            {% else %}
              <span>{{ product.price|currency_format }}</span>
            {% endif %}
          </p>

          {% if product.quantity > 0 %}
            {% if orderitem == None %}
              <a href="{{ product.get_add_item_to_cart_url }}" class="update-cart btn btn-primary btn-md my-0 p" data-action="add" data-slug="{{ product.slug }}" data-pk="{{ product.pk }}">
                Comprar
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>
            {% else %}
                <a href="{{ product.get_remove_item_from_cart_url }}"><i class="update-cart fas fa-minus mr-2" data-action="remove" data-slug="{{ product.slug }}" data-pk="{{ product.pk }}"></i></a>
                {{ orderitem.quantity }}
                {% if product.quantity > orderitem.quantity %}
                  <a href="{{ product.get_add_item_to_cart_url }}"><i class="update-cart fas fa-plus ml-2" data-action="add" data-slug="{{ product.slug }}" data-pk="{{ product.pk }}"></i></a>
                {% endif %}
            {% endif %}
            <p class="mt-3">Quantidade disponível: {{ product.quantity }}</p>
          {% else %}
            <p>Produto indisponível no momento!</p>
          {% endif %}
          
        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Descrição</h4>

        <p>{{ product.description|safe|linebreaks }}</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <hr>

    {% if related_items %}
    <h5 class="mt-5 mb-3 text-center">Produtos Relacionados</h5>

    <div class="mb-3 row d-flex justify-content-center wow fadeIn">
      {% for related_prod in related_items %}
        
        <div class="card text-center" style="border-style:ridge; margin: 2px;">
          <a href="{{ related_prod.get_url }}">
            <img src="{{ related_prod.image.url }}" width="150px" class="img-fluid">
          </a>
          <div class="card-body text-center">
            <a href="{{ related_prod.get_url }}" class="dark-grey-text">
                <strong>{{ related_prod.title|truncatewords_html:5 }}</strong>
            </a>
          </div>
        </div>

      {% endfor %}
    </div>
    {% endif %}
    <!--Grid row-->

  </div>
</main>
<!--Main layout-->
{% endblock %}

templates/profile-menu.html
<div class="row">
  <div class="col-md-3 mb-4">
    <hr class="mb-4">
    <div class="card">

      <a class="btn btn-dark btn-lg text-left" href="{% url 'profile-user-data' %}">
        <i class="fas fa-id-card" style='color: white'></i>
        Dados Pessoais
      </a>

      <a class="btn btn-dark btn-lg text-left" href="{% url 'profile-user-address' 'read' 'profile' %}">
        <i class="fas fa-address-book" style='color: white'></i>
        Endereços
      </a>

      <a class="btn btn-dark btn-lg text-left"  href="{% url 'profile-user-orders' %}">
        <i class="fas fa-list-ol" style='color: white'></i>
        Pedidos
      </a>

    </div>
  </div>